version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-researchhub
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=UTC
      - N8N_SECURE_COOKIE=false
      - N8N_DISABLE_PRODUCTION_MAIN_PROCESS=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ./:/home/node/.n8n/custom-workflows
    networks:
      - n8n_network

volumes:
  n8n_data:

networks:
  n8n_network:
    driver: bridge
