[build]
command = "npm install && npm run build:server"

[deploy]
startCommand = "node dist/server/server/index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
    